#!/bin/sh

KONG_API_HOST=$KONG_API_HOST KONG_API_PORT=$KONG_API_PORT API_NAME=$API_NAME API_UPSTREAM=$API_UPSTREAM API_REQUEST_PATH=$API_REQUEST_PATH ./add-api.sh
KONG_API_HOST=$KONG_API_HOST KONG_API_PORT=$KONG_API_PORT API_NAME=$API_NAME ./add-plugins.sh
